# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-18 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20230215_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to='mailing.Mailing'),
        ),
    ]
