# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-25 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_auto_20230220_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='time_planned_send',
            field=models.DateTimeField(default='2022-02-01'),
            preserve_default=False,
        ),
    ]
